service: calculator

provider:
  name: aws
  runtime: nodejs4.3
  role: arn:aws:iam::616103791264:role/lambda_basic_execution

functions:
  add:
    handler: build/functions/add/add.addition
    events:
      - http:
          path: add
          method: post
          cors: true
  divide:
    handler: build/functions/divide/divide.division
    events:
      - http:
          path: divide
          method: post
          cors: true
  multiply:
    handler: build/functions/multiply/multiply.multiplication
    events:
      - http:
          path: multiply
          method: post
          cors: true
  subtract:
    handler: build/functions/subtract/subtract.subtraction
    events:
      - http:
          path: subtract
          method: post
          cors: true
          
plugins:
  - serverless-offline